### ISSUE TITLE
[Android] UI 및 기능 수정 

### ISSUE THREAD

**Issue by kmj-99** [kookmin-sw/capstone-2024-22#180]
## 💡 Feature Issue

UI 및 기능 수정

## 🌿  Tasks

- [x] 설정 화면에서 녹음 관련 질문 삭제
- [x] 녹음 저장시 네트워크 연결이 안되어 있으면 토스트 메시지 띄우기
- [x] 녹음 툴팁 메시지 3~5초후 사라지게 수정
- [x] 녹음 클릭시 바로 녹음 되게 수정
- [x] 홈화면에서 당일 여행일 경우 디자인 수정
- [x] 여행 추가할 때 중복될 경우 토스트 메시지 띄우기
